openapi: 3.0.0
info:
  title: User Authentication API
  description: |
    This API handles user authentication and token management. It provides endpoints for user login, user creation, and JWT token validation.
  version: 1.0.0
servers:
  - url: /R401/r401-Auth/api
    description: Development server
paths:
  /endpoint.php:
    post:
      summary: Authenticate user and generate JWT token
      description: Authenticates a user by verifying their username and password. If valid, generates a JWT token.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username of the user.
                password:
                  type: string
                  description: The password of the user.
              required:
                - username
                - password
      responses:
        '200':
          description: User identified successfully. Returns the JWT token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The generated JWT token.
        '400':
          description: Error wrong credential or invalid request.
    put:
      summary: Create a new user
      description: Creates a new user with the provided username and password.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username for the new user.
                password:
                  type: string
                  description: The password for the new user.
              required:
                - username
                - password
      responses:
        '201':
          description: User created successfully.
        '400':
          description: Error while creating the user or invalid request.
    get:
      summary: Validate JWT token
      description: Validates the provided JWT token.
      tags:
        - Authentication
      parameters:
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
          description: Bearer token for authentication.
      responses:
        '200':
          description: Token is valid.
        '400':
          description: Invalid Token.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          description: The username of the user.
        password:
          type: string
          description: The password of the user.
      required:
        - username
        - password
    Token:
      type: object
      properties:
        token:
          type: string
          description: The generated JWT token.
      required:
        - token
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message.
        code:
          type: integer
          description: Error code.
      required:
        - message
        - code
    ValidationError:
      type: object
      properties:
        message:
          type: string
          description: Validation error message.
        code:
          type: integer
          description: Validation error code.
      required:
        - message
        - code
    UserCreated:
      type: object
      properties:
        message:
          type: string
          description: User created successfully message.
        code:
          type: integer
          description: Success code.
      required:
        - message
        - code
    UserNotFound:
      type: object
      properties:
        message:
          type: string
          description: User not found error message.
        code:
          type: integer
          description: User not found error code.
      required:
        - message
        - code
    InvalidCredentials:
      type: object
      properties:
        message:
          type: string
          description: Invalid credentials error message.
        code:
          type: integer
          description: Invalid credentials error code.
      required:
        - message
        - code
      